name: build

on:
  push:
    branches:
    - master
    paths:
    - *.ipynb
    - solutions/*.ipynb

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive-xetex pandoc
        pip install jupyter nbconvert
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Clean colab metadata
      run: |
        python .github/clean_colab_metadata.py *.ipynb solutions/*.ipynb
        git add .
        git commit -m "🧹 Clean colab metadata" || echo "No changes to commit"
    - name: Compile PDFs
      run: |
        jupyter nbconvert --to pdf --output-dir=solutions/pdf solutions/*.ipynb
        git add solutions/pdf/
        git commit -m "📄 Compile PDFs" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}